language: objective-c

osx_image: xcode9

install:
  - nvm install 6
  - rm -Rf "${TMPDIR}/jest_preprocess_cache"
  - brew install yarn --ignore-dependencies
  - brew install watchman
  - yarn install

script:
  - if [[ "$TEST_TYPE" = objc-ios ]]; then travis_retry travis_wait 30 ./client/scripts/objc-test-ios.sh test; fi

cache:
  - cocoapods
  - yarn

matrix:
  - fast_finish: true # Fail the whole build as soon as one test type fails. Should help with Travis capacity issues (very long queues).

# The order of these tests says which are more likely to run first and fail the whole build fast.
env:
  - TEST_TYPE=objc-ios

branches:
  only:
    - master
    - dev
    - /^.*-stable$/

notifications:
  email:
    recipients:
      - rhuansantosdev@gmail.com
    on_failure: change
    on_success: change
